### ISSUE TITLE
Lack of code documentation

### ISSUE THREAD

**Issue by scmmmh** [nandoflorestan/kajiki#18]
I've been using Kajiki on two projects recently and found it really nice to use. However, at the moment there is a significant lack of code documentation, which makes it a lot harder to contribute to the project, particularly when I run into bugs. It would be nice if some time could be spent on the documentation, then I could provide pull-requests with fixes rather than just bug-reports.

**Comment by amol-** [comment]
I usually prefer clear and expressive function/classes names to comments (which tend to get off-sync with what the code is actually doing) but I recognize that some parts of kajiki do not provide a clear and expressive name nor are documented so they might be hard to grasp.

Luckily Kajiki has a pretty simple codebase:
 - `loader.py` provides support for loading template from files.
 - `xml_template.py` and `text.py` just compile the template and emit the intermediate representation of the template as `ir nodes` (whatever IR means, I rally don't know why it's named IR but in the end it's just which python code should be emitted for each xml/text node).
 - `ir.py` contains which python code should be emitted for each node of the intermediate representation
 - `template.py` contains the global template object (including the `__kj__` object) which is used by emitted python code to store state of things (like I'm currently inside a `py:switch`, or inside a `py:with`) and to provide some utility functions.

Everything else is pretty much support of utilities which you can usually ignore until you face them :D

I'll try to comment at least classes and modules to explain their scope, so that it should be easier for new contributors at least to have a better graps of the flow. That should provide a first step in the right direction.

**Comment by scmmmh** [comment]
I'm with you all the way on the function/class names. Nothing worse than comments that tell you nothing more than the function/class name or that are incorrect.

Thanks for the high-level overview. That is exactly what I was looking for. That should also allow me to re-work the pull request I sent into a cleaner solution.

I'll also try and spend a bit of time on the front-facing user documentation, if you don't mind.

**Comment by nandoflorestan** [comment]
FWIW, "IR" means "intermediate representation" in the compiler sense. Kajiki is a compiler, it transforms a template into a logical tree and then into Python code which is finally run against a context dictionary.

**Comment by amol-** [comment]
e1141f8ee6353fec13e5ebb39a655e67896e39ba

adds some comments related to core parse of template parsing.

**Comment by scmmmh** [comment]
That looks good. Thank you for that.
