### ISSUE TITLE
Jinja & Django like template filters?

### ISSUE THREAD

**Issue by amol-** [nandoflorestan/kajiki#27]
A commonly used template feature is filters in the form `somevalue | filter | filter(option)` to transform the value in various ways. Usually to format it properly for rendering.

In Jinja this is provided through a specific piece of parser and compiler that parse `|` to a filter.

The same seems to me can be achieved by not parsing filters at all and forcing them to subclass a common base class that relies on ``__ror__`` like::

```
class TemplateFilter(object):
    """Base Class for all filters"""
    def apply(self, value, *args, **kwargs):
      raise NotImplementedError('Filters must implement this')
    def __init__(self, *args, **kwargs):
      self.args, self.kwargs = args, kwargs
    def __call__(self, *args, **kwargs):
      return self.__class__(*args, **kwargs)
    def __ror__(self, input):
      return self.apply(input, *self.args, **self.kwargs)


class WrapWithFilter(TemplateFilter):
    """Wraps the whole content in a given tag"""
    def apply(self, value, tag):
      return '<{tag}>{value}</{tag}>'.format(tag=tag, value=value)
```

Than `"something" | WrapWithFilter('strong')` will render to `<strong>something</strong>`

@nandoflorestan @rick446 do you think there is any use case we can only achieve by implementing filters at parser/compiler level? Because I see the implementation based on operator overloading far easier to achieve and maintain.

**Comment by nandoflorestan** [comment]
I am sorry for asking this, but what is the value of a filters feature?

(I am sure you didn't expect this question, but can you please try to answer it?)

I mean, as far as I understand them, filters are just another way of calling a function. The only difference is, in the template syntax the argument to the function is to the left of the function name. `"blabla" | safe` is equivalent to `safe("blabla")`.

I think filters originated from the daft concept in Django templates, that the templating language should be limited in what it could do. The creators of Django thought it would be too dangerous to allow designers to call a function. Template writers were not to be trusted with such powers. But later they had to allow functions to be called from the template, so they created filters. Which is a nonsensical decision: now instead of writing a simple function, the programmer has to go through documentation to write a '''Filter'''.

But Genshi and Kajiki do the right thing, they allow the template to call functions and methods, so I never felt the need for a filter.

Further, filters make the syntax that much more different from Python, which in my opinion is to be avoided.

Jinja is a reimplementation of Django templates, therefore it has filters. But in Jinja, too, you can call a function -- this is one of the most important "improvements" that Jinja offers over Django templates!

Another question: There exist packages for Python with implementations of pipes, such that, when programming in Python, you can create pipelines of function calls, using the "pipe" operator. Witness https://pypi.python.org/pypi/pipe/1.4.1 -- Would the result of a filter feature in Kajiki be any different from usage of one of these packages?

I am probably being myopic in this opinion of mine, since a few templating languages do provide filters. Please do enlighten me -- what am I missing?

(By the way, Alessandro, congratulations on the great job you've been doing on Kajiki!)

**Comment by amol-** [comment]
Thanks @nandoflorestan that's pretty much the kind of discussion I was looking for regarding this change.

Like you stated filters are pretty much plain functions, and I always used helpers for that and considered filters superfluous myself.

During the years I noticed by the way a few TG users asking for them. 
During the various discussions the two points pro filers that have been pointed out to me I find most interesting are:
  - Filters are better when multiple one are involved `users | map(attribute='username') | join(', ')` is more readable than `join(map(users, attribute='username'), ', ')` 
  - Being better suited to usage by combining multiple ones they foster usage of multiple small reausable tools instead of helpers like `h.format_user`. (This might in fact be a bad thing or a good thing depending on how you see it, updating a filter chain in 200 different templates is surely worse than updating a single helper.)

One more thing that came to my mind is that filters are small pieces of code that we can ship together with kajiki itself. Being small it would be easy for people to contribute back their own in case they need more, and that might be a way to involve contributors. Once they already cloned the code and had a look at it to contribute a filter the barrier to play around with other parts of the engine is then reduced.

The `pipe` package in fact is implemented exactly like my snippet above ( https://github.com/JulienPalard/Pipe/blob/master/pipe.py#L379 ) so it might be a candidate for an implementation based on `__ror__` instead of a new parser token. 

I would by the way avoid including a dependency for that.

**Comment by nandoflorestan** [comment]
This is what I can see:

Forces IN FAVOR of implementing filters:

- Readability in the rare cases where there are chained function calls.

Reasons that Alessandro gave for implementing filters, but I don't understand:

- Building a library of filters. Why, I am in favor of providing, in Kajiki, a rich library of helper functions. Not sure why we are conflating this with the discussion on filters. These should be separate discussions, no?
- A library of helper functions can be made of functions that follow the UNIX design philosophy of doing only one thing and doing it well. This also has very little to do with the discussion on whether or not to build filters. Of course I can see that filters are more convenient and readable for chaining, but the functions themselves should be well factored independently of whether the user will use them as functions or filters.
- Alessandro says he wouldn't depend on the ``pipe`` package, but doesn't say why. I just hope this isn't NIH or that silly thought so many programmers have, that dependencies are a bad thing (Django I am looking at you, you are famous for including everything and being a monolith and not reusing libraries).

Forces AGAINST implementing filters:

- Doesn't seem necessary. YAGNI.
- Filters are not Pythonic in the sense that they aren't a feature of Python syntax, so why are we insisting on having filters in the templating language, in a place where we expect Python?
- Django templates (and Jinja) only have filters because of a bad design decision.
- Whoever decides they need filters can simply use the *pipe* package or something similar.
- I do not for one second believe what you say, that the filters feature will bring to the project contributors writing filters.
- There are important features that Kajiki is lacking and really needs without a doubt, such as better internationalization. (Genshi i18n is better.) So we should not spend resources on something whose value is doubtful.
- Kajiki, when created by Rick Copeland, carefully avoided the misfeatures of Genshi, such as Match templates and XInclude. Filters seem to me to be just one of those misfeatures.

I reserve the right to be wrong and to change my opinion as soon as someone shows me better reasons. But today, this is my opinion. My opinion shouldn't count for much, Alessandro is doing the real work now. So I am fine if Alessandro decides to implement filters in Kajiki. I'm just glad I was given the opportunity to give my opinion.

Alessandro, I am not using Kajiki at work because of the i18n. That's where the focus really should be.

**Comment by amol-** [comment]
Could you please open an issue with the issues you are facing with i18n? I think it greatly helps having a reference of what we need to fix.

**Comment by amol-** [comment]
CLosing as rejected
